### ISSUE TITLE
Tailwind.merge does not handle objects correctly

### ISSUE THREAD

**Issue by rolandschuetz** [CarbonPackages/Carbon.Eel#11]
**Describe the bug**
[The docu describes[(https://github.com/CarbonPackages/Carbon.Eel?tab=readme-ov-file#tailwindmergemixed1-mixed2-mixedn) that `Tailwind.merge('one', ['one', 'two'], {three: true, four: false})` should result in `'one two three'`, actually its `'one two true'`

Tesed with carbon/eel 2.15.0 with and neos/neos 8.3.9

**Comment by jonnitto** [comment]
https://github.com/CarbonPackages/Carbon.Eel/releases/tag/2.15.1

**Comment by rolandschuetz** [comment]
Great, this works. Thanks for the prompt fix! :)
