### ISSUE TITLE
@propTypes ERROR in Carbon.Eel:BEM because of typing error in modifier

### ISSUE THREAD

**Issue by PetraWeinmueller** [CarbonPackages/Carbon.Eel#2]
Carbon.Eel:BEM @propTypes typing error in modifier "**PopTypes**"

modifier = ${PropTypes.anyOf( PropTypes.string, **PopTypes**.arrayOf( PropTypes.any ) )}

musst be

modifier = ${PropTypes.anyOf( PropTypes.string, **PropTypes**.arrayOf( PropTypes.any ) )}

**Comment by jonnitto** [comment]
Hi @PetraWeinmueller 

Thank you a lot for your issue. I fixed this with [Version 1.7.1](https://github.com/CarbonPackages/Carbon.Eel/releases/tag/1.7.1)
